# Generated by Django 6.0.7 on 2026-09-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('stock_quantities', models.IntegerField()),
                ('purchases', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
